### ISSUE TITLE
Project proposal

### ISSUE THREAD

**Issue by OhBall** [akim0409/AuTube#1]
MVP List:

- [x] Unless you have any objections, we should stick to the MVP guidelines for this project, where the MVP's are: 

    - Video upload and playback
    - Likes/dislikes for videos
    - Comments
    - Search
    - Bonus: Number of plays
    - Bonus: Upvotes/downvotes for comments
    - Bonus: Channels and subscriptions

     If you'd like to have a private dashboard of videos, I think it would make sense to implement as a part of / after channels and subscriptions.

Schema:
- [x] While you'll have to use AWS in order to host your videos, your `videos` table will still need some sort of `url` column. For now, feel free to just make it a `string` before we go over AWS.

- [x] Views probably don't need to be their own table. A `views` or `view_count` column on the `videos` table should suffice.

**Comment by jliversi** [comment]
Backend Routes
- [ ] For our user routes, does `GET to /api/users` return all users information? Should you also add a route to just return a single users info (ex. `GET /api/users/:id`) Other than that one minor thing, your backend routes look great. 

Frontend Routes 
- [ ] For some of your components, I think you may be better of splitting up some of the responsibilities and having more subcomponents. For example, in your video show page, it's a lot for the video VideoShowComponent to handle EVERYTHING on that page except for comments. Consider having that component have children such as "VideoPlayerComponent" and "VideoInfoComponent" (where the title and description might go), etc.
- [ ] For the videoShow page, should there be a component for the sideBar on the right which shows related/recommended videos? Where would this go in our frontend and what subcomponents might it need?
