### ISSUE TITLE
User_auth review

### ISSUE THREAD

**Issue by akim0409** [akim0409/AuTube#3]
## user_auth

- [ ] MVP is completely styled and seeded
- [x] MVP is bug free with smooth navigation
- [x] MVP is bug free on a hard refresh (⌘ + shift + R)
- [ ] MVP handles errors with informative messages for user

**Comment by jliversi** [comment]
Hey Autumn, great work so far, I just have a few notes for things to fix for your user_auth: 

- [ ] Demo user link doesn’t work, is currently just text. 
- [ ] On the sign in page, the "Sign In" text at the top should be slightly bigger, and the "to continue to autube" text should be slightly less bold
- [ ] Same on sign up page ("Sign Up" should be bigger, "to continue to autube" should be less bold)
- [ ] Errors (especially for signup), should be rendered under their specific fields, and should be red. For example, if your password is too short, that message should appear under the password field. Currently they all just appear at the top. Let me know if you have trouble implementing this and I can give some guidance. 
- [ ] Sign in/Sign up buttons should be slightly taller.
